In [3]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [4]:
!ls '/content/drive/MyDrive'

'Citizen AI explanation .mp4'
'Colab Notebooks'
'Copy of  Artificial Intelligence (1).docx'
'Copy of  Artificial Intelligence (2).docx'
'Copy of  Artificial Intelligence.docx'
'Deen Mohammed_Python Resume .pdf'
'Deen mohammed Resume.pdf'
'Deen Mohammed_Web Developer  (1).pdf'
'Deen Mohammed_Web Developer  (2).pdf'
'Deen Mohammed_Web Developer .pdf'
'Deen Resume.pdf'
'DM img .jpg'
'Gen Ai for Software dev.pdf'
'Generative Ai .pdf'
'IBM DA0151EN Certificate  edX.pdf'
'IBM DV0151EN Certificate  edX.pdf'
'IBM .jpeg'
'IBM RP0101EN Certificate  edX.pdf'
 IMG_4997.jpeg
'LLm basics.pdf'
 nascom.jpeg
 nasscom.png
 netflix_titles.csv
'Power of Ai Agents.pdf'
'review 1.png'
 Servicenow.jpeg
 SHAIK_DEEN_MOHAMMED_CV.docx
 SHAIK_DEEN_MOHAMMED_CV.pdf
 Shaik_Deen_Mohammed_DM.pdf
'Shaik_Deen_Mohammed_Resume___ (1).pdf'
'SHAIK DEEN MOHAMMED-Resume (1).pdf'
'Shaik_Deen_Mohammed_Resume___ (2).pdf'
 Shaik_Deen_Mohammed_Resume_CustomerService.pdf
 Shaik_Deen_Mohammed_____Resume____.pdf
 Shaik_Deen_Mohammed_Resume___.pdf
'SHAIK DEEN MOHAMMED-Resume.pdf'

In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/netflix_titles.csv')
df.shape

IsADirectoryError: [Errno 21] Is a directory: '/content/drive/MyDrive/netflix_titles.csv'

In [7]:
!ls -F '/content/drive/MyDrive'

'Citizen AI explanation .mp4'
'Colab Notebooks'/
'Copy of  Artificial Intelligence (1).docx'
'Copy of  Artificial Intelligence (2).docx'
'Copy of  Artificial Intelligence.docx'
'Deen Mohammed_Python Resume .pdf'
'Deen mohammed Resume.pdf'
'Deen Mohammed_Web Developer  (1).pdf'
'Deen Mohammed_Web Developer  (2).pdf'
'Deen Mohammed_Web Developer .pdf'
'Deen Resume.pdf'
'DM img .jpg'
'Gen Ai for Software dev.pdf'
'Generative Ai .pdf'
'IBM DA0151EN Certificate  edX.pdf'
'IBM DV0151EN Certificate  edX.pdf'
'IBM .jpeg'
'IBM RP0101EN Certificate  edX.pdf'
 IMG_4997.jpeg
'LLm basics.pdf'
 nascom.jpeg
 nasscom.png
 netflix_titles.csv/
'Power of Ai Agents.pdf'
'review 1.png'
 Servicenow.jpeg
 SHAIK_DEEN_MOHAMMED_CV.docx
 SHAIK_DEEN_MOHAMMED_CV.pdf
 Shaik_Deen_Mohammed_DM.pdf
'Shaik_Deen_Mohammed_Resume___ (1).pdf'
'SHAIK DEEN MOHAMMED-Resume (1).pdf'
'Shaik_Deen_Mohammed_Resume___ (2).pdf'
 Shaik_Deen_Mohammed_Resume_CustomerService.pdf
 Shaik_Deen_Mohammed_____Resume____.pdf
 Shaik_Deen_Mohammed_Resume___.pdf
'SHAIK DEEN MOHAMMED-Resume.pdf'

In [8]:
!ls -F '/content/drive/MyDrive/netflix_titles.csv'

netflix_titles.csv

In [9]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/netflix_titles.csv/netflix_titles.csv')
df.shape

(8807, 12)

In [10]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [12]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df[df['rating'].str.contains('min', na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [15]:
df  = df.drop_duplicates()
df.shape

(8807, 12)

In [16]:
df['date_added'] = pd.to_datetime(df['date_added'].str.strip(), errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [17]:
wrong = df['rating'].str.contains('min', na=False)
df.loc[wrong, 'duration'] = df.loc[wrong, 'rating']
df.loc[wrong, 'rating'] = np.nan

In [18]:
df[df['rating'].str.contains('min', na=False)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [19]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Not Rated')

In [20]:
df = df.dropna(subset=['date_added', 'duration'])
df.shape

(8797, 12)

In [21]:
df.isnull().sum()
df.shape

(8797, 12)

In [22]:
df.to_csv('/content/drive/MyDrive/netflix_cleaned.csv', index=False)

In [23]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Not Rated')

/tmp/ipykernel_3855/318937822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['director'] = df['director'].fillna('Unknown')
/tmp/ipykernel_3855/318937822.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cast'] = df['cast'].fillna('Unknown')
/tmp/ipykernel_3855/318937822.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'] = df['country'].fillna('Unknown')
/tmp/ipykernel_3855/318937822.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].fillna('Not Rated')

In [24]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [25]:
df = df.dropna(subset=['date_added', 'duration'])
df.shape

(8797, 12)

In [26]:
df.isnull().sum()
df.shape

(8797, 12)

In [27]:
df.to_csv('/content/drive/MyDrive/netflix_cleaned.csv', index=False)